// Importing required package modules
package com.cashcontrol.entity;

import java.time.LocalDate;

import jakarta.annotation.sql.DataSourceDefinition;
// Importing required classes (using jakarta.persistence now)
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder

public class Transactions {
    /*
     * Transactions entity definition.
     * userID is autogenerated, so is created at.
     * DO NOT TRY AND SPECIFY USER ID, THIS BREAKS EVERYTHING.
     * I SPENT AN HOUR TRYING TO FIGURE OUT WHY IT WAS BROKE.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long transactionID;
    private Long userID;
    private String transactionType;
    private Long amount;
    private LocalDate dateHelper = LocalDate.now();
    private String category;
    private String description = "";
    private Long createdAt = System.currentTimeMillis();
}
