// Importing required package modules
package com.cashcontrol.entity;

import jakarta.annotation.sql.DataSourceDefinition;
// Importing required classes (using jakarta.persistence now)
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder

public class Users {
    /*
     * Database entity definition.
     * userID is autogenerated, so is created at.
     * DO NOT TRY AND SPECIFY USER ID, THIS BREAKS EVERYTHING.
     * I SPENT AN HOUR TRYING TO FIGURE OUT WHY IT WAS BROKE.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long userID;
    private String name;
    private String email;
    //time created stored as unix millis
    private Long createdAt = System.currentTimeMillis();

}
